# Usamos una imagen oficial de Nginx
FROM nginx:alpine

# Copiamos los archivos del proyecto en el contenedor
COPY . /usr/share/nginx/html

# Exponemos el puerto 80 para acceder al servidor
EXPOSE 80
